version: '3'

services:
  frontend:
    container_name: frontend
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:5173'
    # depends_on:
    #   - backend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    env_file:
      - ./.env
    command: ['yarn', 'dev']
